version: "1.0"
mode: sequential
fail_fast: ${{FAIL_FAST_VAR}}
strict_fail_fast: false
stages:
  - main
steps:
  print:
    stage: main
    image: alpine:latest
    commands:
      - echo 'hello, world'
